import { Inter } from 'next/font/google'
import './globals.css'
import './App.css';
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'overflow-x-hidden font-Inter'}>
        {children}
      </body>
    </html>
  )
}
